import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Head from 'next/head';

import { BLACK } from '@constants';

import '../styles/globals.css';
import '../styles/vars.css';

// const geistSans = localFont({
//     src: '../public/fonts/GeistVF.woff',
//     variable: '--font-geist-sans',
//     weight: '100 900',
// });
// const geistMono = localFont({
//     src: '../public/fonts/GeistMonoVF.woff',
//     variable: '--font-geist-mono',
//     weight: '100 900',
// });

export const metadata: Metadata = {
    title: 'Star Wars Fan Page',
    description: 'Generated by me (it actually was)',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Head>
                <meta charSet="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>Star Wars Fan Page</title>
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link
                    href="https://fonts.googleapis.com/css2?family=Orbitron:wght@400..900&family=Roboto+Mono:ital,wght@0,100..700;1,100..700&display=swap"
                    rel="stylesheet"
                />
            </Head>
            <body style={{ margin: '0', background: BLACK }}>{children}</body>
        </html>
    );
}
