import type { Metadata } from 'next';
import Image from 'next/image';

import { ButtonCarousel, Character } from '@components';

import { getRandomNumber } from '@utils';

import Joke from './joke';
import {
    Body,
    ContentBox,
    RoutingLink,
    ScrollingSpan,
    ScrollingText,
    Title,
    WayBackExtraFooter,
} from './page-styles';

export const metadata: Metadata = {
    title: 'Star Wars Fan Page',
    description: 'Generated by me (it actually was)',
};

export default function Home() {
    const jokeNum = getRandomNumber(0, 137);

    return (
        <Body>
            <Title>Welcome to my retro homepage!</Title>
            <ScrollingText>
                <ScrollingSpan>
                    &ldquo;A long time ago in a galaxy far, far away...&rdquo; — Welcome to the
                    ultimate Star Wars fan page!
                </ScrollingSpan>
            </ScrollingText>
            <ContentBox>
                <h2>Latest News</h2>
                <p>
                    The Empire is expanding! Stay tuned for the next adventure in a galaxy far, far
                    away.
                </p>
            </ContentBox>
            <ContentBox>
                <h2>Choose Your Side</h2>
                <p>
                    Will you join the <RoutingLink href="/light-side">Rebellion</RoutingLink>, or
                    embrace the <RoutingLink href="/dark-side">Dark&nbsp;Side?</RoutingLink>
                    new homepage <RoutingLink href="/">Home page</RoutingLink>
                </p>
            </ContentBox>
            <Joke randomNumber={jokeNum} />
            <ContentBox>
                <Image
                    alt="Luke Skywalker & Darth Vader"
                    height={300}
                    src="https://art.pixilart.com/5990002c63e1151.png"
                    style={{ height: '100%', width: '100%' }}
                    width={400}
                />
            </ContentBox>
            <ButtonCarousel />
            <Character />
            <WayBackExtraFooter>
                May the Force be with you! &copy; 1999 Star Wars Fan Club
            </WayBackExtraFooter>
        </Body>
    );
}
